from enum import Enum

from pydantic import BaseModel


class ErrorCode(str, Enum):
    # Document upload errors
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    INVALID_MIME_TYPE = "INVALID_MIME_TYPE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    DOCUMENT_LIMIT_REACHED = "DOCUMENT_LIMIT_REACHED"
    EMPTY_FILE = "EMPTY_FILE"
    NO_EXTRACTABLE_TEXT = "NO_EXTRACTABLE_TEXT"
    EMBEDDING_RATE_LIMIT = "EMBEDDING_RATE_LIMIT"
    EMBEDDING_UNAVAILABLE = "EMBEDDING_UNAVAILABLE"
    PARSE_FAILURE = "PARSE_FAILURE"

    # Chat errors
    EMPTY_QUERY = "EMPTY_QUERY"
    QUERY_TOO_LONG = "QUERY_TOO_LONG"
    NO_DOCUMENTS_READY = "NO_DOCUMENTS_READY"
    LLM_RATE_LIMIT = "LLM_RATE_LIMIT"
    LLM_UNAVAILABLE = "LLM_UNAVAILABLE"
    LLM_EMPTY_RESPONSE = "LLM_EMPTY_RESPONSE"
    RETRIEVAL_FAILURE = "RETRIEVAL_FAILURE"


class ErrorResponse(BaseModel):
    error_code: str
    message: str
    details: dict | None = None
