#!/usr/bin/env bash
# Generated by pivota-spec init-dev-server
# Catalog entry: agent-synthesized
# Generator version: init-dev-server@1
#
# Edits ABOVE the END PIVOTA PREAMBLE marker are reset on regen.
# Edits BELOW the marker are preserved on regen.
#
# Why these choices (decision-trace; do not delete):
#   - `set -euo pipefail` not just `-e` — RESEARCH.md Pitfall 4 (silent pipe failures).
#   - `sha256sum` for lockfile hashing — RESEARCH.md "Don't hand-roll" (universal
#     coreutils, no extra dep vs blake3 / git hash-object / md5sum).
#   - Backoff 1s / 2s / 4s — Claude's Discretion per CONTEXT.md (small base, predictable).
#   - Log destination `/tmp/pivota-dev.log` — Open Question #4 resolved (always
#     writable inside Daytona sandboxes; matches existing convention).
#   - Lockfile-sentinel skip combined with INSTALL_PRESENCE_CHECK — RESEARCH.md
#     Pitfall 6 (sentinel survives reboots but install output dirs may not on
#     fresh tmpfs; never skip on a clean directory).
#   - Retry exits with INNER command's last exit code (not a fixed 1) so callers
#     can disambiguate failures from the wrapper.
#   - run_install has an npm ERESOLVE fallback (--legacy-peer-deps) + a FATAL
#     marker (D-12.1) — a scaffold with a lagging peer range must not silently
#     leave node_modules empty and hang the preview on "Waiting to bind".
#   - Agent-synthesized: monorepo with React+Vite frontend (frontend/) and
#     FastAPI backend (backend/). Multi-process: bash trap + wait -n per
#     RESEARCH.md Pattern 3 and multi-process-template.md.
#   - Frontend vite.config.ts sets port 3000 with proxy to backend:8000.
#     Wrapper forwards --host 0.0.0.0 to Vite and a vite.config.pivota.ts
#     overlay is generated to relax allowedHosts for sandbox preview embedding.
#   - Backend runs uvicorn with --host 0.0.0.0 --port 8000 --reload inside a
#     Python venv. No external DB: SQLite (rag_chatbot.db) is self-contained
#     and initialized at app startup by init_db().

set -euo pipefail

# === Bash version guard (RESEARCH.md Pitfall 8) ===
# `wait -n` (used by the multi-process variant) requires bash >= 4.3.
# Fail fast with a clear message; do not silently degrade.
if (( BASH_VERSINFO[0] < 4 )) || { (( BASH_VERSINFO[0] == 4 )) && (( BASH_VERSINFO[1] < 3 )); }; then
  echo "[pivota] bash 4.3+ required for 'wait -n'; found ${BASH_VERSION}" >&2
  exit 127
fi

# === Single-instance guard ===
# Multiple platform paths can invoke the wrapper concurrently (sandbox setup,
# preview open, verify pre-flight) — observed as two launch trees racing in one
# sandbox. Second invocation exits 0 quietly: the first boot is authoritative
# and callers poll the port, not this process.
exec 200>/tmp/pivota-dev.lock
if ! flock -n 200; then
  echo "[pivota] start-dev.sh already running (lock held) — exiting; poll the ready port instead" >&2
  exit 0
fi

# === D-11.4: tee stdout/stderr to /tmp/pivota-dev.log AND pass through ===
mkdir -p /tmp
exec > >(tee -a /tmp/pivota-dev.log) 2>&1
echo "[pivota] $(date -Iseconds) start-dev.sh begin (catalog: agent-synthesized)"

# === D-11.1 + D-11.2: per-stack 0.0.0.0 binding + host allowlist relaxation ===
# Vite does NOT honor VITE_HOST or VITE_ALLOWED_HOSTS env vars (RESEARCH.md Pitfall 1).
# Vite binding is forced via --host 0.0.0.0 in the frontend process CMD below.
# allowedHosts relaxation is via vite.config.pivota.ts overlay (see Pre-exec below).
export HOST=0.0.0.0
# Uvicorn honors UVICORN_HOST / UVICORN_PORT (uvicorn.org/settings/).
export UVICORN_HOST=0.0.0.0
export UVICORN_PORT=8000
# Unbuffered for SSE log streaming (RESEARCH.md Pitfall 5).
export PYTHONUNBUFFERED=1

# === D-11.3: .env.example -> .env seed (platform-injection-safe) ===
# Backend .env: seed from backend/.env.example if backend/.env is missing.
if [[ ! -f backend/.env && -f backend/.env.example ]]; then
  echo "[pivota] seeding backend/.env from backend/.env.example (preserving platform-injected vars)"
  while IFS= read -r line || [[ -n "$line" ]]; do
    trimmed="${line#"${line%%[![:space:]]*}"}"
    if [[ "$trimmed" == \#* || -z "$trimmed" || "$trimmed" != *"="* ]]; then
      printf '%s\n' "$line"; continue
    fi
    key="${trimmed#export }"; key="${key%%=*}"; key="${key//[[:space:]]/}"
    if [[ -n "${!key+x}" ]]; then
      printf '# [pivota] %s omitted — provided by platform environment\n' "$key"
      continue
    fi
    if [[ "$line" != *\"* && "$line" != *\'* ]]; then
      line="$(printf '%s' "$line" | sed -E 's/[[:space:]]+#.*$//')"
    fi
    value="${line#*=}"
    value_lc="$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')"
    if [[ "$value_lc" == change_me* || "$value_lc" == changeme* ]]; then
      generated="$(head -c 48 /dev/urandom | base64 | tr -dc 'A-Za-z0-9')"
      printf '%s=%s\n' "$key" "${generated:0:48}"
      echo "[pivota] generated random value for placeholder $key" >&2
    else
      printf '%s\n' "$line"
    fi
  done < backend/.env.example > backend/.env
fi

# Frontend .env: seed from frontend/.env.example if frontend/.env is missing.
if [[ ! -f frontend/.env && -f frontend/.env.example ]]; then
  echo "[pivota] seeding frontend/.env from frontend/.env.example (preserving platform-injected vars)"
  while IFS= read -r line || [[ -n "$line" ]]; do
    trimmed="${line#"${line%%[![:space:]]*}"}"
    if [[ "$trimmed" == \#* || -z "$trimmed" || "$trimmed" != *"="* ]]; then
      printf '%s\n' "$line"; continue
    fi
    key="${trimmed#export }"; key="${key%%=*}"; key="${key//[[:space:]]/}"
    if [[ -n "${!key+x}" ]]; then
      printf '# [pivota] %s omitted — provided by platform environment\n' "$key"
      continue
    fi
    if [[ "$line" != *\"* && "$line" != *\'* ]]; then
      line="$(printf '%s' "$line" | sed -E 's/[[:space:]]+#.*$//')"
    fi
    value="${line#*=}"
    value_lc="$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')"
    if [[ "$value_lc" == change_me* || "$value_lc" == changeme* ]]; then
      generated="$(head -c 48 /dev/urandom | base64 | tr -dc 'A-Za-z0-9')"
      printf '%s=%s\n' "$key" "${generated:0:48}"
      echo "[pivota] generated random value for placeholder $key" >&2
    else
      printf '%s\n' "$line"
    fi
  done < frontend/.env.example > frontend/.env
fi

# === Pre-exec snippet ===
# 1) Vite allowedHosts overlay (react-vite catalog pattern).
#    Write vite.config.pivota.ts inside frontend/ ONLY if allowedHosts is absent.
if [[ -f frontend/vite.config.ts && ! -f frontend/vite.config.pivota.ts ]]; then
  if ! grep -q "allowedHosts" frontend/vite.config.ts 2>/dev/null; then
    cat > frontend/vite.config.pivota.ts <<'VITEEOF'
// Auto-generated by pivota init-dev-server. Extends user's vite.config.ts at runtime
// to set server.allowedHosts = true (sandbox preview embedding) and host=true (so
// the dev server binds 0.0.0.0). Remove this file if you set allowedHosts yourself.
import { defineConfig, mergeConfig } from 'vite';
import userConfig from './vite.config';
export default defineConfig((env) => mergeConfig(
  typeof userConfig === 'function' ? userConfig(env) : userConfig,
  { server: { host: true, allowedHosts: true, strictPort: true } }
));
VITEEOF
    echo "[pivota] wrote frontend/vite.config.pivota.ts (allowedHosts overlay)"
  fi
fi

# 2) Python venv bootstrap for backend (idempotent).
if [[ -f backend/requirements.txt && ! -d backend/.venv ]]; then
  echo "[pivota] creating backend/.venv from requirements.txt"
  python3 -m venv backend/.venv
fi
if [[ -d backend/.venv ]]; then
  # shellcheck disable=SC1091
  source backend/.venv/bin/activate
fi

# === D-12: idempotent frontend install via lockfile hash + presence check ===
SENTINEL="/tmp/pivota-setup-sentinel"
LOCK_FILE_PATH="frontend/package-lock.json"
INSTALL_PRESENCE_CHECK="frontend/node_modules"
INSTALL_CMD='cd frontend && npm ci || npm install'

run_install() {
  echo "[pivota] running install: $INSTALL_CMD"
  local rc=0
  bash -c "$INSTALL_CMD" || rc=$?
  if (( rc == 0 )); then
    return 0
  fi
  if [[ "$INSTALL_CMD" == *"npm "* ]]; then
    echo "[pivota] WARN install failed (exit=$rc) — retrying with --legacy-peer-deps"
    local rc2=0
    (cd frontend && npm install --legacy-peer-deps) || rc2=$?
    if (( rc2 == 0 )); then
      echo "[pivota] WARN install succeeded via --legacy-peer-deps fallback — fix package.json"
      return 0
    fi
    rc=$rc2
  fi
  echo "[pivota] FATAL install failed (exit=$rc) — dev server cannot start" >&2
  return "$rc"
}

if [[ -n "$LOCK_FILE_PATH" && -f "$LOCK_FILE_PATH" ]]; then
  CURRENT_HASH=$(sha256sum "$LOCK_FILE_PATH" | cut -d' ' -f1)
  PREVIOUS_HASH=$(cat "$SENTINEL" 2>/dev/null || echo "")
  PRESENCE_OK=1
  if [[ -n "$INSTALL_PRESENCE_CHECK" && ! -e "$INSTALL_PRESENCE_CHECK" ]]; then
    PRESENCE_OK=0
  fi
  if [[ "$CURRENT_HASH" == "$PREVIOUS_HASH" && "$PRESENCE_OK" == "1" ]]; then
    echo "[pivota] lockfile unchanged AND install output present; skipping frontend install"
  else
    if [[ "$PRESENCE_OK" == "0" ]]; then
      echo "[pivota] install output ($INSTALL_PRESENCE_CHECK) missing; install required"
    else
      echo "[pivota] lockfile changed (or first boot); install required"
    fi
    run_install
    echo "$CURRENT_HASH" > "$SENTINEL"
  fi
elif [[ -n "$INSTALL_CMD" ]]; then
  if [[ ! -f "$SENTINEL" ]]; then
    run_install
    touch "$SENTINEL"
  fi
fi

# === D-12: idempotent backend install via requirements hash + presence check ===
SENTINEL_BACKEND="/tmp/pivota-setup-sentinel-backend"
LOCK_FILE_BACKEND="backend/requirements.txt"
INSTALL_PRESENCE_CHECK_BACKEND="backend/.venv/lib"
INSTALL_CMD_BACKEND='cd backend && pip install -r requirements.txt'

run_install_backend() {
  echo "[pivota] running backend install: $INSTALL_CMD_BACKEND"
  local rc=0
  bash -c "$INSTALL_CMD_BACKEND" || rc=$?
  if (( rc != 0 )); then
    echo "[pivota] FATAL backend install failed (exit=$rc) — dev server cannot start" >&2
    return "$rc"
  fi
}

if [[ -f "$LOCK_FILE_BACKEND" ]]; then
  CURRENT_HASH_BE=$(sha256sum "$LOCK_FILE_BACKEND" | cut -d' ' -f1)
  PREVIOUS_HASH_BE=$(cat "$SENTINEL_BACKEND" 2>/dev/null || echo "")
  PRESENCE_OK_BE=1
  if [[ -n "$INSTALL_PRESENCE_CHECK_BACKEND" && ! -e "$INSTALL_PRESENCE_CHECK_BACKEND" ]]; then
    PRESENCE_OK_BE=0
  fi
  if [[ "$CURRENT_HASH_BE" == "$PREVIOUS_HASH_BE" && "$PRESENCE_OK_BE" == "1" ]]; then
    echo "[pivota] requirements.txt unchanged AND venv present; skipping backend install"
  else
    if [[ "$PRESENCE_OK_BE" == "0" ]]; then
      echo "[pivota] backend venv lib ($INSTALL_PRESENCE_CHECK_BACKEND) missing; install required"
    else
      echo "[pivota] requirements.txt changed (or first boot); backend install required"
    fi
    run_install_backend
    echo "$CURRENT_HASH_BE" > "$SENTINEL_BACKEND"
  fi
elif [[ ! -f "$SENTINEL_BACKEND" ]]; then
  run_install_backend
  touch "$SENTINEL_BACKEND"
fi

# === Defense-in-depth bash version guard (multi-process — RESEARCH.md Pitfall 8) ===
if (( BASH_VERSINFO[0] < 4 )) || { (( BASH_VERSINFO[0] == 4 )) && (( BASH_VERSINFO[1] < 3 )); }; then
  echo "[pivota] multi-process block requires bash 4.3+ for wait -n; found ${BASH_VERSION}" >&2
  exit 127
fi

# === Multi-process supervision: React+Vite frontend + FastAPI backend ===
# Pattern: bash trap + background PIDs + wait -n (RESEARCH.md Pattern 3).
# DO NOT use concurrently / pm2 / supervisord — bash is zero-dep and uniform.
shutdown() {
  echo "[pivota] shutting down children"
  kill -TERM "${PIDS[@]}" 2>/dev/null || true
  # Brief grace, then SIGKILL stragglers (RESEARCH.md Pitfall 3: npm SIGTERM)
  sleep 2
  kill -KILL "${PIDS[@]}" 2>/dev/null || true
  wait
}
trap shutdown SIGTERM SIGINT EXIT

declare -a PIDS=()

# --- Backend: FastAPI via uvicorn ---
# Entry point is backend/app/main.py:app. Run from backend/ dir so relative
# paths in config (VECTOR_STORE_PATH=./data/chroma, DATABASE_URL=rag_chatbot.db)
# resolve correctly. --host 0.0.0.0 binds for sandbox preview access.
# PYTHONUNBUFFERED=1 already exported above for SSE streaming.
(
  cd backend \
    && : \
    && exec bash -c 'uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload'
) 2>&1 | sed 's/^/[backend] /' &
PIDS+=($!)

# --- Frontend: Vite dev server ---
# vite.config.ts already sets port 3000 and proxies /api to localhost:8000.
# --host 0.0.0.0 forces external binding; the pivota overlay config also sets
# allowedHosts: true for sandbox preview iframe embedding.
(
  cd frontend \
    && : \
    && exec bash -c 'npm run dev -- --config vite.config.pivota.ts --host 0.0.0.0 2>/dev/null || npm run dev -- --host 0.0.0.0'
) 2>&1 | sed 's/^/[frontend] /' &
PIDS+=($!)

# Wait for ANY child to exit; if one dies, the trap tears down siblings.
wait -n
EXIT_CODE=$?
shutdown
exit "$EXIT_CODE"

# === END PIVOTA PREAMBLE ===
# Below this marker, projects may add custom shutdown / setup logic.
# This region is PRESERVED across regenerations (plan 06's regen logic detects
# the marker and re-appends user content verbatim after re-emitting the preamble).
